INSERT INTO produit (nomProduit, marqueProduit, descriptionProduit, prixProduit, idCategorie) VALUES
('Carotte','Bonduel','Légume orange riche en protéines',1.00,1),
('Poireau','Géant Vert','Légume vert plein de fibre',1.20,1),
('Citrouille','Cascina Belvedere','Légume orange parfait pour les fêtes d''Halloween',1.95,1),
('Brie','Président','Fromage de caractère au lait de vache',16.50,2),
('Comté','Entremont','Fromage au lait cru',15.05,2),
('Lait','Candia','Produit laitier semi-écrémé',0.70,2),
('Bière','Chouffe','Boisson alcoolisée à base d''orge et d''houblon',3.78,3),
('Eau','Evian','Eau de source',0.57,3),
('Coca','Coca cola','Boisson gazeuse sucrée',1.10,3),
('Javel','Monsieur Propre','Solution liquide oxydante désinfectante et décolorante',7.92,4),
('Lave vitre','Kärcher','Solution nettoyante spéciale fenêtre',3.71,4),
('Liquide vaisselle','Paic','Liquide vaisselle super dégraissant',9.23,4),
('Parfum','Channel','Fragrance délicate et boisée',56.48,5),
('Rouge à lèvre','Velvet','Produit de cosmétique permettant de souligner les lèvres',34.50,5),
('Fond de teint','Maybelline','Produit cosmétique permettant d''unifier et de protéger l''épiderme',28.90,5),
('Television HD','Samsung','Poste de télévision permettant l''emission et la reception de séquences audiovisuelles',299.99,6),
('Smartphone','Sony','GSM nouvelle génération',149.90,6),
('Rasoir éléctrique','Phillips','Rasoir performant et plus ergonomique pour un meilleur rasage de la moustache',72.04,6),
('Carotte','Grand Frais','Légume orange riche en protéines',1.20,1),
('Poireau','Cassegrin','Légume vert plein de fibre',1.04,1),
('Citrouille','Nos régions ont du talent','Légume orange parfait pour les fêtes d''Halloween',2.25,1),
('Brie','Coeur de lion','Fromage de caractère au lait de vache',14.99,2),
('Comté','Juraflore','Fromage au lait cru',12.50,2),
('Lait','Lactel','Produit laitier semi-écrémé',0.98,2),
('Bière','Kronenbourg','Boisson alcoolisée à base d''orge et d''houblon',1.25,3),
('Eau','Vittel','Eau de source',0.48,3),
('Coca','Pepsi','Boisson gazeuse sucrée',1.02,3),
('Javel','Saint Marc','Solution liquide oxydante désinfectante et décolorante',6.54,4),
('Lave vitre','Ecovacs','Solution nettoyante spéciale fenêtre',2.60,4),
('Liquide vaisselle','Mir','Liquide vaisselle super dégraissant',12.60,4),
('Parfum','Dior','Fragrance délicate et boisée',46.38,5),
('Rouge à lèvre','L''Oreal','Produit de cosmétique permettant de souligner les lèvres',41.20,5),
('Fond de teint','Bourjois','Produit cosmétique permettant d''unifier et de protéger l''épiderme',32.50,5),
('Television HD','LG','Poste de télévision permettant l''emission et la reception de séquences audiovisuelles',199.90,6),
('Smartphone','Apple','GSM nouvelle génération',780.00,6),
('Rasoir éléctrique','Wilkinson','Rasoir performant et plus ergonomique pour un meilleur rasage de la moustache',68.22,6),
('Petits pois','Bonduel','Le must des petits pois',1.60,1),
('Pommes de terre','Géant Vert','Des patates. toujours des patates',1.90,1),
('Artichaux','Cascina Belvedere','Superbe pièce murit à souhait',1.30,1),
('Petits pois','Cascina Belvedere','Le must des petits pois',1.30,1),
('Pommes de terre','Géant Vert','Des patates. toujours des patates',1.70,1),
('Artichaux','Cascina Belvedere','Superbe pièce murit à souhait',2.00,1),
('Tomates','Bonduel','Bien ronde et bien rouge',1.80,1),
('Brocolis','Géant Vert','Beau brocolis vert',1.60,1),
('Haricots Verts','Cascina Belvedere','Haricots vert made in France',1.90,1),
('Tomates','Cascina Belvedere','Bien ronde et bien rouge',1.60,1),
('Brocolis','Géant Vert','Beau brocolis vert',1.30,1),
('Haricots Verts','Cascina Belvedere','Haricots vert made in France',1.80,1),
('Choux fleur','Géant Vert','Choux fleur de nos régions',1.90,1),
('Choux de bruxelles','Géant Vert','Choux belges plusieurs fois primés',1.20,1),
('Flageolets','Cascina Belvedere','Flageolets bien ferme et de taille suffisante',1.10,1),
('Choux fleur','Cascina Belvedere','Choux fleur de nos régions',1.90,1),
('Choux de bruxelles','Géant Vert','Choux belges plusieurs fois primés',1.90,1),
('Flageolets','Cascina Belvedere','Flageolets bien ferme et de taille suffisante',1.60,1),
('Emmentale','Président','Emmentale de montagne',2.50,2),
('Brie','Entremont','Brie de nos régions',2.20,2),
('Lait chocolat en brique','Candia','Idéal pour le goûter',3.00,2),
('Crème fraiche','Président','Idéale pour la cuisine',2.50,2),
('Fromage en portion','Entremont','Petites portions à emmener partout',3.00,2),
('Gruyère','Candia','Gruyère à déguster ou à ajouter dans vos plats',2.50,2),
('Fromage à raclette','Président','Idéal pour une raclette en famille ou amis',2.70,2),
('Fromage à tartiner','Entremont','Fromage à tartiner idéal pour l''apéro',2.70,2),
('Emmentale','Candia','Emmentale de montagne',2.20,2),
('Brie','Entremont','Brie de nos régions',2.30,2),
('Lait chocolat en brique','Candia','Idéal pour le goûter',2.70,2),
('Crème fraiche','Président','Idéale pour la cuisine',3.00,2),
('Fromage en portion','Entremont','Petites portions à emmener partout',2.40,2),
('Gruyère','Entremont','Gruyère à déguster ou à ajouter dans vos plats',2.20,2),
('Fromage à raclette','Président','Idéal pour une raclette en famille ou amis',2.60,2),
('Fromage à tartiner','Candia','Fromage à tartiner idéal pour l''apéro',2.40,2),
('Fondue','Candia','Fondue savoyarde',2.10,2),
('Lait de chèvre','Candia','Pour ceux qui aiment le chèvre',3.00,2),
('Fondue','Entremont','Fondue savoyarde',2.20,2),
('Lait de chèvre','Entremont','Pour ceux qui aiment le chèvre',3.00,2),
('Eau de vie','Arthurus','Le meilleur pour les fin de soirée',2.30,3),
('Mirabelle','Moureyus','Idéal pour donner un peu de goût à vos repas',2.30,3),
('Calva','Alcolus','Pour les hommes. les vrais',3.00,3),
('Marc','PuRienBus','Marc mûrit en fût pendant 7 mois',2.70,3),
('Whisky','Jack Daniels','Le seul. l''unique',2.80,3),
('Vin','Veuve cliquot','Vin de grande qualité',2.10,3),
('Snaps','Deutshus','Artoung ça décoiffe',2.70,3),
('Jus de raisin','Materne','Jus de raisin 100% pur fruit',2.20,3),
('Jus de pomme','Normalus','Pommes issue de l''agriculture biologique',2.60,3),
('Eau de vie','Asbach','Le meilleur pour les fin de soirée',2.80,3),
('Mirabelle','Adam','Idéal pour donner un peu de goût à vos repas',3.00,3),
('Calva','Deutshus','Pour les hommes. les vrais',2.10,3),
('Marc','Alcolus','Marc mûrit en fût pendant 7 mois',2.20,3),
('Whisky','Shivas','Le seul. l''unique',2.30,3),
('Vin','Saint Émilion','Vin de grande qualité',3.00,3),
('Snaps','Moureyus','Artoung ça décoiffe',2.80,3),
('Jus de raisin','Normalus','Jus de raisin 100% pur fruit',2.60,3),
('Jus de pomme','Materne','Pommes issue de l''agriculture biologique',3.00,3),
('Déodorisant WC','Monsieur Propre','Idéal pour sentir bon où ça ne sent pas bon',3.90,4),
('Nettoyant WC','Kärcher','Nettoyage suprême des zones de guerres',3.60,4),
('Eponge','Paic','A utiliser avec de l''huile de coude',3.60,4),
('Nettoyant sol','Monsieur Propre','Mettre un bouchon dans 5 litres d''eau',3.30,4),
('Déboucheur canalisation','Kärcher','Idéal pour le transit de vos canalisations. Ne pas ingérer',3.10,4),
('Chiffon vitre','Paic','Ne fonctionne pas avec les écrans d''ordinateur',3.50,4),
('Bombe dépoussiérante','Monsieur Propre','Idéal pour dépoussiérer',3.10,4),
('Balai','Kärcher','Ne sert pas à voler. mais à nettoyer',3.90,4),
('Serpillère','Paic','Serpillère 100% pure coton',3.90,4),
('Déodorisant WC','Kärcher','Idéal pour sentir bon où ça ne sent pas bon',3.20,4),
('Nettoyant WC','Paic','Nettoyage suprême des zones de guerres',3.10,4),
('Eponge','Monsieur Propre','A utiliser avec de l''huile de coude',3.10,4),
('Nettoyant sol','Kärcher','Mettre un bouchon dans 5 litres d''eau',3.10,4),
('Déboucheur canalisation','Paic','Idéal pour le transit de vos canalisations. Ne pas ingérer',3.80,4),
('Chiffon vitre','Monsieur Propre','Ne fonctionne pas avec les écrans d''ordinateur',3.80,4),
('Bombe dépoussiérante','Kärcher','Idéal pour dépoussiérer',4.00,4),
('Balai','Paic','Ne sert pas à voler. mais à nettoyer',3.80,4),
('Serpillère','Monsieur Propre','Serpillère 100% pure coton',3.80,4),
('Poudre BB','Channel','Poudre pour jouer au ninja dans un nuage de fumé',60.90,5),
('Eye liner','Velvet','Pour des maquillages réussis',57.70,5),
('Mascarat waterproof','Maybelline','Ne résiste pas à la piscine',73.90,5),
('Gloss','Channel','Pour augmenter la taille de vos lèvres',75.90,5),
('Phare à paupière','Velvet','Ne sert pas à attirer les bateaux',6.70,5),
('Pince à épiler','Maybelline','Sert également à tirer les vers du nez',176.60,5),
('Bande de cire','Channel','100% avec douleurs',119.10,5),
('Coton tige','Velvet','100% pure fibre de coton',123.90,5),
('Crème hydrante','Maybelline','Hydrate la peau en profondeur',173.50,5),
('Eau miscellaire','Channel','Idéal pour se démaquiller',55.10,5),
('Anti cernes','Velvet','Pour les lendemains de soirée',131.50,5),
('Poudre BB','Channel','Poudre pour jouer au ninja dans un nuage de fumé',48.20,5),
('Eye liner','Velvet','Pour des maquillages réussis',58.90,5),
('Mascarat waterproof','Maybelline','Ne résiste pas à la piscine',178.20,5),
('Gloss','Channel','Pour augmenter la taille de vos lèvres',158.50,5),
('Phare à paupière','Velvet','Ne sert pas à attirer les bateaux',82.70,5),
('Pince à épiler','Maybelline','Sert également à tirer les vers du nez',199.70,5),
('Bande de cire','Channel','100% avec douleurs',69.60,5),
('Coton tige','Velvet','100% pure fibre de coton',105.20,5),
('Crème hydrante','Maybelline','Hydrate la peau en profondeur',114.70,5),
('Eau miscellaire','Channel','Idéal pour se démaquiller',75.50,5),
('Anti cernes','Maybelline','Pour les lendemains de soirée',78.30,5),
('Four à microonde','Samsung','Four à microonde haut de gamme',94.40,6),
('Aspirateur','Sony','Aspirateur sans fil et sans sac',24.30,6),
('Grille pain','Phillips','Idéal pour vos tartines du matin',80.70,6),
('Ordinateur','Samsung','Ordinateur top moumoute plus',77.00,6),
('Tablette','Sony','Tablette idéal pour vos envies de mobilité',66.20,6),
('Chaine HiFI','Phillips','Chaine HiFi avec son HD',122.30,6),
('Radio','Samsung','Capter toutes vos radios préférées',194.80,6),
('Ecran PC','Sony','Ecran 15 pouces LED',37.10,6),
('Four à microonde','Sony','Four à microonde haut de gamme',148.80,6),
('Aspirateur','Phillips','Aspirateur sans fil et sans sac',61.10,6),
('Grille pain','Samsung','Idéal pour vos tartines du matin',130.20,6),
('Ordinateur','Sony','Ordinateur top moumoute plus',54.50,6),
('Tablette','Phillips','Tablette idéal pour vos envies de mobilité',23.50,6),
('Chaine HiFI','Samsung','Chaine HiFi avec son HD',35.90,6),
('Radio','Sony','Capter toutes vos radios préférées',21.30,6),
('Ecran PC','Phillips','Ecran 15 pouces LED',59.80,6),
('Montre connectée','Apple','Montre connectée répondant à tous vos besoins',177.60,6);